development:
  sessions:
    default:
      database: chicken
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: chicken_test
      hosts:
        - localhost:27017
